// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Author      string `json:"author"`
	Isbn        string `json:"isbn"`
	PublishedAt string `json:"publishedAt"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type CreateBookInput struct {
	Title       string `json:"title"`
	Author      string `json:"author"`
	Isbn        string `json:"isbn"`
	PublishedAt string `json:"publishedAt"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateBookInput struct {
	Title       *string `json:"title,omitempty"`
	Author      *string `json:"author,omitempty"`
	Isbn        *string `json:"isbn,omitempty"`
	PublishedAt *string `json:"publishedAt,omitempty"`
}
